// Code generated by protols (pathbuilder). DO NOT EDIT.
// source: github.com/kralicky/codegen/pathbuilder/pathbuilder.proto

package pathbuilder

import (
	protopath "google.golang.org/protobuf/reflect/protopath"
)

type (
	generatorOptionsPathBuilder protopath.Path
)

func (*GeneratorOptions) ProtoPath() generatorOptionsPathBuilder {
	return generatorOptionsPathBuilder{protopath.Root(((*GeneratorOptions)(nil)).ProtoReflect().Descriptor())}
}

func (p generatorOptionsPathBuilder) Enabled() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*GeneratorOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
