// Code generated by protols (pathbuilder). DO NOT EDIT.
// source: github.com/kralicky/codegen/cli/cli.proto

package cli

import (
	protopath "google.golang.org/protobuf/reflect/protopath"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

type (
	generatorOptionsPathBuilder    protopath.Path
	flagOptionsPathBuilder         protopath.Path
	flagSetOptionsPathBuilder      protopath.Path
	anyPathBuilder                 protopath.Path
	commandGroupOptionsPathBuilder protopath.Path
	commandOptionsPathBuilder      protopath.Path
)

func (*GeneratorOptions) ProtoPath() generatorOptionsPathBuilder {
	return generatorOptionsPathBuilder{protopath.Root(((*GeneratorOptions)(nil)).ProtoReflect().Descriptor())}
}
func (*FlagOptions) ProtoPath() flagOptionsPathBuilder {
	return flagOptionsPathBuilder{protopath.Root(((*FlagOptions)(nil)).ProtoReflect().Descriptor())}
}
func (*FlagSetOptions) ProtoPath() flagSetOptionsPathBuilder {
	return flagSetOptionsPathBuilder{protopath.Root(((*FlagSetOptions)(nil)).ProtoReflect().Descriptor())}
}
func (*CommandGroupOptions) ProtoPath() commandGroupOptionsPathBuilder {
	return commandGroupOptionsPathBuilder{protopath.Root(((*CommandGroupOptions)(nil)).ProtoReflect().Descriptor())}
}
func (*CommandOptions) ProtoPath() commandOptionsPathBuilder {
	return commandOptionsPathBuilder{protopath.Root(((*CommandOptions)(nil)).ProtoReflect().Descriptor())}
}

func (p flagSetOptionsPathBuilder) Default() anyPathBuilder {
	return anyPathBuilder(append(p, protopath.FieldAccess(((*FlagSetOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}

func (p generatorOptionsPathBuilder) Enabled() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*GeneratorOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p generatorOptionsPathBuilder) GenerateDeepcopy() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*GeneratorOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p generatorOptionsPathBuilder) GenerateFlagsForAllMessages() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*GeneratorOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p generatorOptionsPathBuilder) ClientDependencyInjection() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*GeneratorOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p flagOptionsPathBuilder) Default() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*FlagOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p flagOptionsPathBuilder) Env() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*FlagOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p flagOptionsPathBuilder) Secret() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*FlagOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(3))))
}
func (p flagOptionsPathBuilder) TypeOverride() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*FlagOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(4))))
}
func (p flagOptionsPathBuilder) Skip() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*FlagOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(5))))
}
func (p flagSetOptionsPathBuilder) NoPrefix() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*FlagSetOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p anyPathBuilder) TypeUrl() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*anypb.Any)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(1))))
}
func (p anyPathBuilder) Value() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*anypb.Any)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(2))))
}
func (p commandGroupOptionsPathBuilder) Use() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandGroupOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25601))))
}
func (p commandGroupOptionsPathBuilder) GroupId() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandGroupOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25602))))
}
func (p commandGroupOptionsPathBuilder) EnableHooks() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandGroupOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25603))))
}
func (p commandOptionsPathBuilder) Use() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25601))))
}
func (p commandOptionsPathBuilder) Aliases(idx int) protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25602)), protopath.ListIndex(idx)))
}
func (p commandOptionsPathBuilder) RequiredFlags(idx int) protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25603)), protopath.ListIndex(idx)))
}
func (p commandOptionsPathBuilder) Skip() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25604))))
}
func (p commandOptionsPathBuilder) EnableHooks() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25605))))
}
func (p commandOptionsPathBuilder) Granularity() protopath.Path {
	return protopath.Path(append(p, protopath.FieldAccess(((*CommandOptions)(nil)).ProtoReflect().Descriptor().Fields().ByNumber(25606))))
}
