// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: github.com/kralicky/codegen/openapiv2/openapiv2.proto

package openapiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratorOptions_Format int32

const (
	GeneratorOptions_Swagger   GeneratorOptions_Format = 0
	GeneratorOptions_OpenapiV3 GeneratorOptions_Format = 1
)

// Enum value maps for GeneratorOptions_Format.
var (
	GeneratorOptions_Format_name = map[int32]string{
		0: "Swagger",
		1: "OpenapiV3",
	}
	GeneratorOptions_Format_value = map[string]int32{
		"Swagger":   0,
		"OpenapiV3": 1,
	}
)

func (x GeneratorOptions_Format) Enum() *GeneratorOptions_Format {
	p := new(GeneratorOptions_Format)
	*p = x
	return p
}

func (x GeneratorOptions_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeneratorOptions_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_enumTypes[0].Descriptor()
}

func (GeneratorOptions_Format) Type() protoreflect.EnumType {
	return &file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_enumTypes[0]
}

func (x GeneratorOptions_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeneratorOptions_Format.Descriptor instead.
func (GeneratorOptions_Format) EnumDescriptor() ([]byte, []int) {
	return file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescGZIP(), []int{0, 0}
}

type GeneratorOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Format  bool `protobuf:"varint,2,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *GeneratorOptions) Reset() {
	*x = GeneratorOptions{}
	mi := &file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratorOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorOptions) ProtoMessage() {}

func (x *GeneratorOptions) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorOptions.ProtoReflect.Descriptor instead.
func (*GeneratorOptions) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratorOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GeneratorOptions) GetFormat() bool {
	if x != nil {
		return x.Format
	}
	return false
}

var file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*GeneratorOptions)(nil),
		Field:         25700,
		Name:          "openapiv2.generator",
		Tag:           "bytes,25700,opt,name=generator",
		Filename:      "github.com/kralicky/codegen/openapiv2/openapiv2.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional openapiv2.GeneratorOptions generator = 25700;
	E_Generator = &file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_extTypes[0]
)

var File_github_com_kralicky_codegen_openapiv2_openapiv2_proto protoreflect.FileDescriptor

var file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDesc = []byte{
	0x0a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61,
	0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76,
	0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69,
	0x76, 0x32, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x24, 0x0a, 0x06, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x56, 0x33, 0x10, 0x01,
	0x3a, 0x5c, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe4, 0xc8, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61,
	0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescOnce sync.Once
	file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescData = file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDesc
)

func file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescGZIP() []byte {
	file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescOnce.Do(func() {
		file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescData)
	})
	return file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDescData
}

var file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_goTypes = []any{
	(GeneratorOptions_Format)(0),     // 0: openapiv2.GeneratorOptions.Format
	(*GeneratorOptions)(nil),         // 1: openapiv2.GeneratorOptions
	(*descriptorpb.FileOptions)(nil), // 2: google.protobuf.FileOptions
}
var file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_depIdxs = []int32{
	2, // 0: openapiv2.generator:extendee -> google.protobuf.FileOptions
	1, // 1: openapiv2.generator:type_name -> openapiv2.GeneratorOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_init() }
func file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_init() {
	if File_github_com_kralicky_codegen_openapiv2_openapiv2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_goTypes,
		DependencyIndexes: file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_depIdxs,
		EnumInfos:         file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_enumTypes,
		MessageInfos:      file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_msgTypes,
		ExtensionInfos:    file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_extTypes,
	}.Build()
	File_github_com_kralicky_codegen_openapiv2_openapiv2_proto = out.File
	file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_rawDesc = nil
	file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_goTypes = nil
	file_github_com_kralicky_codegen_openapiv2_openapiv2_proto_depIdxs = nil
}
